/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:01d7d937-13de-4f1f-818c-d246e6d2d1d2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4rq4JdhhJ",
    "aws_user_pools_web_client_id": "726ad2e2invnfhnksv2rgd4g2t",
    "oauth": {}
};


export default awsmobile;
